spring:
  application:
    name: negocio
  #Esto es para la conexión con base de datos PostgreSQL, solo cambiar el name, username, password y url al final.
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/negocio
    username: postgres
    password: 123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Cambia a 'validate', 'create' o 'create-drop' según tu entorno.

server:
  port: 8080